CXX=g++
LIBS=-lcppunit
SOURCES=reverseTest.cc isAnagramTest.cc compStrTest.cc kFromBackTest.cc deleteMidTest.cc moveSmallerTest.cc StackTest.cc
TARGET=algosTest

all :
	g++ -o algosTest algosTest.cc $(SOURCES) $(LIBS)

clean :
	rm $(TARGET)
